### ISSUE TITLE
Lines across screen at screensaver start

### ISSUE THREAD

**Issue by un1versal** [xbmc/screensaver.stars#3]
Cant take a screenshot but good old fashioned pictures dont even do it justice how bad it gets.
makes this otherwise nice screensaver unusable

![20150925_172514](https://cloud.githubusercontent.com/assets/3521959/10106193/2317a69c-63ab-11e5-8f01-382457ce0d10.png)

This is one of the best pictures, it really gets bad.

@notspiff thoughts?

**Comment by notspiff** [comment]
Panic!

That somebody who knows this shit should grok it. I  clumsily ported this
from directx8 to opengl without knowing either standard. Last time i did
graphics a000 was the segment to write to...
25. sep. 2015 18:31 skrev "uNiversaI" <notifications@github.com>:

**Comment by uNiversaI** [comment]
And that means it FUBAR or?

**Comment by AlwinEsch** [comment]
Fixed on Leia.
